name: Publish Release
on:
  push:
    tags:
      - '*'

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [21]
    name: Build and Release Plugin
    runs-on: ${{ matrix.os }}

    permissions:
      packages: write
      contents: write

    steps:
      - name: Print info
        run: |
          export REF="${{ github.ref }}"
          export TAG="${REF##*/}"
          echo "Tag: ${TAG}"
          echo "TAG=${TAG}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}

      - name: Build and Run Tests
        run: |
            ./gradlew --info build || [ -f build/distributions/prometheus-exporter-${{ env.TAG }}.zip  ]

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ env.TAG }}
          tag_name: ${{ env.TAG }}
          files: build/distributions/prometheus-exporter-${{ env.TAG }}.zip
